version: "3.9"
services:
  postgres:
    container_name: security_system_pg_sql
    image: pgvector/pgvector:0.8.0-pg16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - logs:/logs
    ports:
      - "5432:5432"
    restart: unless-stopped

  web:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB_NAME: ${POSTGRES_DB_NAME}
    volumes:
      - .:/app
      - logs:/logs
    ports:
      - "8000:8000"
    depends_on:
      - postgres



volumes:
  postgres:
  logs: